Simplify 'template' program's code, also make second argument optional

diff --git a/dotfiles/bin/template b/dotfiles/bin/template
--- a/dotfiles/bin/template
+++ b/dotfiles/bin/template
@@ -1,72 +1,32 @@
 #!/bin/sh
 
-
-# Config directory precedence
-# 1. $TEMPLATE_CONFIG_DIR
-# 2. $XDG_CONFIG_HOME/template
-# 3. $HOME/.config/template
-if [ -n "$TEMPLATE_CONFIG_DIR" ]; then
-    config_dir="$TEMPLATE_CONFIG_DIR"
-elif [ -n "$XDG_CONFIG_HOME" ]; then
-    config_dir="$XDG_CONFIG_HOME/template"
-else
-    config_dir="$HOME/.config/template"
-fi
-
-library_dir="$config_dir/library"
-file_name="$(basename "$(dirname "$library_dir/$1")")"
+fatal() {
+    echo "$(basename $0): $@"
+    exit 1
+}
 
 
-#
-# Template file checks
-#
+library="${XDG_CONFIG_HOME:-$HOME/.config}/template/library"
+file_name="$(basename "$(dirname "$library/$1")")"
 
 
 if [ -z "$1" ]; then
-    echo "$0: template file is not specified"
-    exit 1
+    fatal "template file was not specified"
 fi
 
-if [ ! -e "$library_dir/$1" ]; then
-    echo "$0: template file does not exist in the library"
-    exit 1
+if [ ! -e "$library/$1" ]; then
+    fatal "template file does not exist in the library"
 fi
 
-if [ ! -f "$library_dir/$1" ]; then
-    echo "$0: template file is not a regular file"
-    exit 1
+if [ ! -f "$library/$1" ]; then
+    fatal "template file is not a regular file"
 fi
 
+[ -n "$2" ] && did_cd=0 && mkdir "$2" && cd "$2" && did_cd=1
 
-#
-# Destination directory checks
-#
-
-
-if [ -z "$2" ]; then
-    echo "$0: destination directory is not specified"
-    exit 1
-fi
-
-if [ ! -e "$2" ]; then
-    echo "$0: destination directory does not exist"
-    exit 1
-fi
-
-if [ ! -d "$2" ]; then
-    echo "$0: destination directory is not a directory"
-    exit 1
-fi
-
-if [ -e "$2/$file_name" ]; then
-    echo "$0: destination directory already has a file named '$file_name'"
-    exit 1
+if [ "$did_cd" = 0 ]; then
+    fatal "destination directory cannot be reached"
 fi
 
 
-#
-# Main
-#
-
-
-cp "$library_dir/$1" "$2/$file_name"
+cp "$library/$1" "$PWD/$filename"
