Handle positional arguments too in 'termshot'

diff --git a/dotfiles/bin/termshot b/dotfiles/bin/termshot
--- a/dotfiles/bin/termshot
+++ b/dotfiles/bin/termshot
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env zsh
 
 usage() {
     cat << EOF
@@ -32,9 +32,10 @@ height="auto"
 # min_height=
 max_height=33
 interactive=0
-output_file=""
+output_file=
+positional=()
 
-while [ "$#" -gt 0 ]; do
+while [[ "$#" -gt 0 ]]; do
     case "$1" in
         --width)
             width="$2"
@@ -76,13 +77,25 @@ while [ "$#" -gt 0 ]; do
             usage
             exit 0
             ;;
-        *)
+        -*)
             echo >&2 "$(tput bold)$(tput setaf 1)Error:$(tput sgr0) Unknown option: $1"
             usage >&2
             exit 1
             ;;
+        *)
+            positional+=("$1")
+            shift 1
+            ;;
     esac
 done
+
+if [[ "${#positional[@]}" -ne 1 ]]; then
+    echo >&2 "$(tput bold)$(tput setaf 1)Error:$(tput sgr0) Expected exactly 1 positional argument."
+    usage >&2
+    exit 1
+fi
+
+input_file="${positional[1]}"
 
 termshot() (
     local output_file="$1"
