Add ability to output to STDOUT

diff --git a/dotfiles/bin/termshot b/dotfiles/bin/termshot
--- a/dotfiles/bin/termshot
+++ b/dotfiles/bin/termshot
@@ -15,11 +15,12 @@ Options:
   -h, --help                                Show this message.
 
 Examples:
-  cat output.txt | $(basename "$0") -o screenshot.png
-  cat output.txt | $(basename "$0") -o screenshot.png --height 33
-  cat output.txt | $(basename "$0") -o screenshot.png --width auto --max-width 100
-  cat output.txt | $(basename "$0") -o screenshot.png --interactive
-  tmux capture-pane -e -p -S - -E - |  $(basename "$0") -o screenshot.png
+  $ cat output.txt | $(basename "$0") -o screenshot.png
+  $ cat output.txt | $(basename "$0") -o screenshot.png --height 33
+  $ cat output.txt | $(basename "$0") -o screenshot.png --width auto --max-width 100
+  $ cat output.txt | $(basename "$0") -o screenshot.png --interactive
+  $ cat output.txt | $(basename "$0") -o - | base64 | pbcopy
+  $ tmux capture-pane -e -p -S - -E - |  $(basename "$0") -o screenshot.png
 EOF
 )"
 
@@ -195,7 +196,21 @@ EOF
         read -s -k
     fi
 
-    screencapture -x -o -l "$window_id" "$output_file"
+    screenshot_file="$(mktemp -t termshot)"
+    screencapture -x -o -l "$window_id" "$screenshot_file"
+    ret="$?"
+    on_exit() { rm -f -- "$content_file" "$screenshot_file"; kill -- "$alacritty_pid"; }
+
+    if [[ "$ret" -ne 0 ]]; then
+        echo >&2 "$(tput bold)$(tput setaf 1)Error:$(tput sgr0) Failed to capture screenshot."
+        exit 1
+    fi
+
+    if [[ "$output_file" == "-" ]]; then
+        cat "$screenshot_file"
+    else
+        cat "$screenshot_file" > "$output_file"
+    fi
 }
 
 main
